"""
This is a setup.py script generated by Gemini to package the Yoinker application for macOS.

Usage on macOS:
1. Install py2app:
   pip3 install -U py2app

2. Build the application and disk image:
   python3 setup.py py2app
"""
import shutil
from setuptools import setup

# --- Find and include ffmpeg ---
ffmpeg_path = shutil.which("ffmpeg")
if not ffmpeg_path:
    raise RuntimeError(
        "ffmpeg not found in your PATH. \n"
        "Please install it before building the app (e.g., 'brew install ffmpeg')"
    )

APP = ['yoinker.py']
# This will place the ffmpeg executable in the app's Contents/Resources directory
DATA_FILES = [ffmpeg_path]
OPTIONS = {
    'argv_emulation': False,
    'packages': ['requests', 'musicbrainzngs', 'yt_dlp', 'mutagen'],
    'plist': {
        'CFBundleName': 'Yoinker',
        'CFBundleDisplayName': 'Yoinker',
        'CFBundleGetInfoString': "Music Downloader",
        'CFBundleIdentifier': "com.yoinker.app",
        'CFBundleVersion': "3.0",
        'CFBundleShortVersionString': "3.0",
        'NSHumanReadableCopyright': u"Copyright © 2025, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
